---
# This is the dev compose.yaml
# This docker compose configuration is not meant to be used in a prod environment
# @see https://codeberg.org/huskas-2189/Bookmark#docker-compose for a production configuration.

name: bookmark

services:
  ui:
    container_name: bookmark
    image: node:lts-alpine3.23@sha256:244cc2b53f46f9e876304391d17682b0ddae9ac33491f4857e25e35a36ba7995
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tty: true
    environment:
      CONFIG_FILE: /app/config/config.yaml
    ports:
      - "5173:5173"

  httpd:
    container_name: httpd
    image: httpd
    ports:
      - "8000:80"
    profiles: ["docker-labels"]
    labels:
      - "bookmark.enable=true"
      - "bookmark.app.httpd.icon=apache"
      - "bookmark.app.httpd.name=Httpd"
      - "bookmark.app.httpd.url=http://localhost:8000"
      - "bookmark.app.httpd.roles=bookmark_admin"
      - "bookmark.app.httpd.group=admin"

      - "bookmark.app.httpd2.icon=apache"
      - "bookmark.app.httpd2.name=Httpd 2"
      - "bookmark.app.httpd2.url=http://localhost:8000"
      - "bookmark.app.httpd2.roles=jellyfin_user"
      - "bookmark.app.httpd2.group=admin"
      - "bookmark.app.httpd2.weight=10"
