name: Docker Build

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  IS_MAIN: ${{ github.ref == 'refs/heads/main' }}

jobs:
  gitversion:
    name: "Gitversion ${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.pull_request.number) || github.ref_name }}"
    runs-on: docker
    container: gittools/gitversion:6.8.2-alpine.3.23-10.0
    outputs:
      version: ${{ steps.version.outputs.version }}
      majorMinorPatch: ${{ steps.version.outputs.majorMinorPatch }}
      preReleaseLabel: ${{ steps.version.outputs.preReleaseLabel }}
    steps:
      - name: Install deps
        run: |
          apk add --no-cache \
            jq

      - name: Checkout
        run: |
          set -eu
          cd "$FORGEJO_WORKSPACE"

          git init
          git remote add origin "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}.git"

          git -c credential.helper='!f() {
            echo username=forgejo-actions
            echo password=${FORGEJO_TOKEN}
          }; f' fetch --tags --force --prune origin

          git checkout --detach "$FORGEJO_SHA"

      - name: Get Version
        id: version
        run: |
          GITVERSION_OUTPUT=$(/tools/dotnet-gitversion /output json)
          echo "version=$(echo $GITVERSION_OUTPUT | jq -r '.SemVer')" >> "$FORGEJO_OUTPUT"
          echo "majorMinorPatch=$(echo $GITVERSION_OUTPUT | jq -r '.MajorMinorPatch')" >> "$FORGEJO_OUTPUT"
          echo "preReleaseLabel=$(echo $GITVERSION_OUTPUT | jq -r '.PreReleaseLabel')" >> "$FORGEJO_OUTPUT"

      - name: Display Version
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"

  build-image:
    name: "Build image ${{ github.event_name == 'pull_request' && format('PR #{0}', github.event.pull_request.number) || github.ref_name }}"
    runs-on: docker
    container:
      image: docker:29-cli
    needs:
      - gitversion
    env:
      CODEBERG_URL: "codeberg.org"
      REPO_URL: "codeberg.org/huskas-2189/bookmark"
    steps:
      - name: Is main branch ?
        run: |
          [ "$IS_MAIN" = "true" ] && echo "is main branch" || echo "is not main branch"

      - name: Install Deps
        run: |
          apk add --no-cache \
            git \
            ca-certificates \
            jq \
            nodejs \
            curl

      - name: Set Up Git
        run: |
          git config --global user.name "${FORGEJO_ACTOR}"
          git config --global user.email "bookmark-pipeline@no-reply"

      - name: Checkout
        run: |
          set -eu
          cd "$FORGEJO_WORKSPACE"

          LOGGED_REPO_URL="https://${FORGEJO_ACTOR}:${FORGEJO_TOKEN}@${REPO_URL}.git"

          git init
          git remote add origin "${LOGGED_REPO_URL}"

          git -c credential.helper='!f() {
            echo username=forgejo-actions
            echo password=${FORGEJO_TOKEN}
          }; f' fetch --tags --force --prune origin

          git checkout --detach "$FORGEJO_SHA"

      - name: Setup Version
        run: |
          if [ "$IS_MAIN" = "true" ]; then
            VERSION="${{ needs.gitversion.outputs.version }}"
          else
            VERSION="${{ needs.gitversion.outputs.majorMinorPatch }}-${{ needs.gitversion.outputs.preReleaseLabel }}"
          fi

          echo $VERSION
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build --no-cache -t ${REPO_URL}:${VERSION} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            .

      - name: Install Trivy
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy vulnerability scanner
        id: trivy
        run: |
          trivy image ${REPO_URL}:${VERSION} \
            --format json \
            --output dependency-results.sbom.json \
            --exit-code 1 \
            --ignore-unfixed \
            --pkg-types os,library \
            --scanners vuln \
            --severity CRITICAL,HIGH

      - name: Display Trivy report
        if: always()
        run: |
          trivy convert \
            --format table \
            --scanners vuln \
            --severity CRITICAL,HIGH \
            dependency-results.sbom.json

      - name: Upload Trivy report
        uses: https://data.forgejo.org/forgejo/upload-artifact@v5
        if: always()
        with:
          name: trivy-sbom-report
          path: dependency-results.sbom.json

      - name: Tag images
        if: github.event_name == 'push'
        run: |
          [ "$IS_MAIN" = "true" ] \
            && docker image tag bookmark_tmp ${REPO_URL}:latest || true

      - name: Login registry
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ${CODEBERG_URL} \
            --username "${FORGEJO_ACTOR}" \
            --password-stdin

      - name: Push Image to registry
        if: github.event_name == 'push'
        run: |
          docker image push --all-tags ${REPO_URL}

      - name: Clean up
        if: always()
        run: |
          docker images ${REPO_URL} -q | xargs -r docker rmi -f
          docker logout ${CODEBERG_URL}

  publish-release:
    name: "Publish Release ${{ github.event_name == 'pull_request' && format('PR #{0} (skipped)', github.event.pull_request.number) || github.ref_name }}"
    runs-on: docker
    container:
      image: node:lts
    needs:
      - gitversion
      - build-image
    if: github.event_name == 'push'
    env:
      GIT_CLIFF_VERSION: "2.13.1"
      CHANGELOG_FILE: "CHANGELOG.md"
    steps:
      - name: Install Deps
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            git \
            jq \
            curl

      - name: Setup Version
        run: |
          if [ "$IS_MAIN" = "true" ]; then
            VERSION="${{ needs.gitversion.outputs.version }}"
          else
            VERSION="${{ needs.gitversion.outputs.majorMinorPatch }}-${{ needs.gitversion.outputs.preReleaseLabel }}"
          fi

          echo $VERSION
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          wget "https://github.com/orhun/git-cliff/releases/download/v${GIT_CLIFF_VERSION}/git-cliff-${GIT_CLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf git-cliff-*.tar.gz
          mv git-cliff-${GIT_CLIFF_VERSION}/git-cliff .
          ./git-cliff --init

      - name: Generate pre-release changelog
        if: env.IS_MAIN != 'true'
        run: |
          ./git-cliff \
            --tag "${VERSION}" \
            --ignore-tags='^.*$' \
            -o ${CHANGELOG_FILE} \
            --config ./.forgejo/cliff-prerelease.toml \
            origin/main..HEAD

      - name: Generate release changelog
        if: env.IS_MAIN == 'true'
        run: |
          ./git-cliff \
            --tag "${VERSION}" \
            --topo-order \
            --use-branch-tags \
            --tag-pattern '^[0-9]*\.[0-9]*\.[0-9]$' \
            --unreleased \
            --config ./.forgejo/cliff-release.toml \
            -o ${CHANGELOG_FILE}

      - name: Create Release
        uses: https://data.forgejo.org/actions/forgejo-release@v2.13.4
        with:
          tag: "${{ env.VERSION }}"
          token: "${{ secrets.BOOKMARK_BOT_TOKEN }}"
          override: ${{ env.IS_MAIN != 'true' }}
          direction: upload
          prerelease: ${{ env.IS_MAIN != 'true' }}
          skip-assets: true
          release-notes-file: "${{ env.CHANGELOG_FILE }}"
